import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    'problem-definition',
    'what-is-axon',
    {
      type: 'category',
      label: 'System Architecture',
      items: ['architecture/system-architecture'],
    },
    {
      type: 'category',
      label: 'System Design',
      items: ['architecture/system-design'],
    },
    {
      type: 'category',
      label: 'About Axon',
      items: [
        'aboutaxon/problem-definition'
      ],
    },
    {
      type: 'category',
      label: 'Schema',
      items: ['schema/database-schema'],
    },
    {
      type: 'category',
      label: 'Diagrams',
<<<<<<< Updated upstream
      items: [
        'diagrams/use-case',
        'diagrams/activity'
      ],
    },
      {
      type: 'category',
      label: 'System Architecture',
      items: [
        'system-architecture/system-architecture-overview',
        {
          type: 'autogenerated',
          dirName: 'system-architecture/modules',
        },
      ],
=======
      items: ['diagrams/use-case', 'diagrams/activity'],
    },
    {
      type: 'category',
      label: 'API Contract',
      items: ['reference/api-contract'],
    },
    {
      type: 'category',
      label: 'Tech Stack',
      items: ['reference/tech-stack'],
>>>>>>> Stashed changes
    },
    {
      type: 'category',
      label: 'Technical Reference',
      items: ['reference/technical-reference'],
    },
  ],
};

export default sidebars;
